# Generated by Django 2.0 on 2020-01-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(default='', max_length=100)),
                ('suburb', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('dc', models.CharField(default='', max_length=100)),
                ('detail_type', models.CharField(default='', max_length=100)),
                ('lat', models.CharField(default='', max_length=100)),
                ('ion', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
