# Generated by Django 2.0 on 2020-01-05 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_countrydetails_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrydetails',
            name='test',
        ),
    ]
