# Generated by Django 2.0 on 2019-05-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangePassword',
        ),
        migrations.DeleteModel(
            name='ChangePasswordCode',
        ),
        migrations.DeleteModel(
            name='PasswordResetEmail',
        ),
    ]
