# Generated by Django 2.0 on 2019-05-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190508_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createprofile',
            name='category',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], max_length=30),
        ),
    ]
