# Generated by Django 2.0 on 2019-05-20 04:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_auto_20190520_0508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Profile',
        ),
    ]
