# Generated by Django 2.0 on 2019-05-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_sellercategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellercategory',
            name='category',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Agency', 'Agency')], max_length=30),
        ),
    ]
