# Generated by Django 2.0 on 2019-05-20 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20190520_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellercategory',
            old_name='select_category',
            new_name='category',
        ),
    ]
