# Generated by Django 2.0 on 2019-05-20 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20190520_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellercategory',
            old_name='category',
            new_name='select_category',
        ),
    ]
