# Generated by Django 2.0 on 2019-05-20 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20190520_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellercategory',
            old_name='select_category',
            new_name='select',
        ),
    ]
