# Generated by Django 2.0 on 2019-05-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_profile_select'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='sellercategory',
            name='user',
        ),
        migrations.DeleteModel(
            name='SellerCategory',
        ),
    ]
