# Generated by Django 2.0 on 2019-05-21 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20190521_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='select',
            new_name='brand',
        ),
    ]
