# Generated by Django 2.0 on 2019-05-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20190521_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='brand',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Agency', 'Agency')], help_text='Select Your brand', max_length=30),
        ),
    ]
