# Generated by Django 2.0 on 2019-05-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f0', models.CharField(help_text='maximum length is 50', max_length=50)),
                ('f1', models.CharField(help_text='maximum length is 100', max_length=100)),
                ('f2', models.CharField(max_length=10000)),
                ('f3', models.IntegerField()),
                ('f4', models.IntegerField()),
                ('f5', models.IntegerField()),
                ('f6', models.CharField(max_length=10000)),
                ('f7', models.IntegerField()),
                ('f8', models.IntegerField()),
                ('f9', models.IntegerField()),
                ('f10', models.IntegerField()),
                ('f11', models.IntegerField()),
                ('f12', models.IntegerField()),
                ('f13', models.IntegerField()),
                ('f14', models.IntegerField()),
                ('f15', models.IntegerField()),
                ('f16', models.IntegerField()),
                ('f17', models.IntegerField()),
                ('f18', models.IntegerField()),
                ('f19', models.CharField(help_text='maximum length is 50', max_length=50)),
                ('f20', models.IntegerField()),
                ('f21', models.IntegerField()),
                ('f22', models.CharField(help_text='maximum length is 150', max_length=150)),
                ('f23', models.CharField(help_text='maximum length is 150', max_length=150)),
                ('f24', models.CharField(help_text='maximum length is 50', max_length=50)),
                ('f25', models.CharField(help_text='maximum length is 4000', max_length=4000)),
                ('f26', models.DateTimeField(auto_now=True)),
                ('f27', models.FileField(help_text='image', upload_to='')),
                ('f29', models.FileField(help_text='video', upload_to='')),
                ('f30', models.FileField(help_text='image', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f0', models.CharField(help_text='maximum length is 50', max_length=50)),
                ('f1', models.CharField(help_text='maximum length is 100', max_length=100)),
                ('f2', models.CharField(max_length=10000)),
                ('f3', models.IntegerField()),
                ('f4', models.IntegerField()),
                ('f5', models.IntegerField()),
                ('f6', models.CharField(max_length=10000)),
                ('f7', models.IntegerField()),
                ('f8', models.IntegerField()),
                ('f9', models.IntegerField()),
                ('f10', models.IntegerField()),
                ('f11', models.IntegerField()),
                ('f12', models.IntegerField()),
                ('f13', models.IntegerField()),
                ('f14', models.IntegerField()),
                ('f15', models.IntegerField()),
                ('f16', models.IntegerField()),
                ('f17', models.IntegerField()),
                ('f18', models.IntegerField()),
                ('f19', models.CharField(help_text='maximum length is 50', max_length=50)),
                ('f20', models.IntegerField()),
                ('f21', models.IntegerField()),
                ('f22', models.CharField(help_text='maximum length is 150', max_length=150)),
                ('f23', models.CharField(help_text='maximum length is 150', max_length=150)),
                ('f24', models.CharField(help_text='maximum length is 50', max_length=50)),
                ('f25', models.CharField(help_text='maximum length is 4000', max_length=4000)),
                ('f26', models.DateTimeField(auto_now=True)),
                ('f27', models.FileField(help_text='image', upload_to='')),
                ('f29', models.FileField(help_text='video', upload_to='')),
                ('f30', models.FileField(help_text='image', upload_to='')),
            ],
        ),
    ]
