# Generated by Django 2.0 on 2019-05-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='f27',
            field=models.FileField(help_text='upload image', upload_to=''),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='f29',
            field=models.FileField(help_text='upload video', upload_to=''),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='f30',
            field=models.FileField(help_text='upload image', upload_to=''),
        ),
    ]
