# Generated by Django 2.0 on 2019-09-28 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveddetail',
            name='header',
        ),
        migrations.RemoveField(
            model_name='saveddetail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='saveddetail2',
            name='header',
        ),
        migrations.RemoveField(
            model_name='saveddetail2',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savedheaders',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savedheaders1',
            name='user',
        ),
        migrations.DeleteModel(
            name='SavedDetail',
        ),
        migrations.DeleteModel(
            name='SavedDetail2',
        ),
        migrations.DeleteModel(
            name='SavedHeaders',
        ),
        migrations.DeleteModel(
            name='SavedHeaders1',
        ),
    ]
