# Generated by Django 2.0 on 2019-08-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_posterrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='description',
            field=models.TextField(default='this is the description of the post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posterrent',
            name='description',
            field=models.TextField(default='this is the description of the post'),
            preserve_default=False,
        ),
    ]
