# Generated by Django 2.0 on 2019-09-28 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0002_auto_20190928_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.TextField()),
                ('pricemin', models.TextField()),
                ('pricemax', models.TextField()),
                ('bedmin', models.TextField()),
                ('bedmax', models.TextField()),
                ('notification', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SavedHeaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='saveddetail',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.SavedHeaders'),
        ),
        migrations.AddField(
            model_name='saveddetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
