# Generated by Django 2.0 on 2019-08-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190801_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='latitude',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poster',
            name='longitude',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
