# Generated by Django 2.0 on 2019-09-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190928_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveddetail',
            name='bedmax',
        ),
        migrations.RemoveField(
            model_name='saveddetail',
            name='bedmin',
        ),
        migrations.RemoveField(
            model_name='saveddetail',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='saveddetail',
            name='pricemax',
        ),
        migrations.RemoveField(
            model_name='saveddetail',
            name='pricemin',
        ),
        migrations.AddField(
            model_name='savedheaders',
            name='bedmax',
            field=models.TextField(default='Any'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedheaders',
            name='bedmin',
            field=models.TextField(default='Any'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedheaders',
            name='notification',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedheaders',
            name='pricemax',
            field=models.TextField(default='Any'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedheaders',
            name='pricemin',
            field=models.TextField(default='Any'),
            preserve_default=False,
        ),
    ]
