# Generated by Django 2.0 on 2019-05-20 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190518_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='min_land_size',
        ),
        migrations.DeleteModel(
            name='minLand',
        ),
    ]
