# Generated by Django 2.0 on 2019-09-28 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20190928_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedheaders',
            name='property_type',
            field=models.TextField(default='House'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saveddetail',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_headers_property', to='index.SavedHeaders'),
        ),
    ]
