# Generated by Django 2.0 on 2019-08-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20190819_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='latitude',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='poster',
            name='longitude',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
