# Generated by Django 2.0 on 2019-05-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('index', '0005_auto_20190520_0725'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='maxPrice',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='poster',
            old_name='Max_price',
            new_name='Price',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='Max_bedrooms',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='Min_bedrooms',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='Min_price',
        ),
        migrations.AddField(
            model_name='poster',
            name='Bedrooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poster',
            name='Bathrooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='poster',
            name='Car_spaces',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='poster',
            name='new_or_established',
            field=models.CharField(choices=[('New', 'New'), ('Established', 'Established')], default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='maxBedRooms',
        ),
        migrations.DeleteModel(
            name='minimumBedRooms',
        ),
        migrations.DeleteModel(
            name='minPrice',
        ),
    ]
