# Generated by Django 2.0 on 2019-09-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190823_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='Bathrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='poster',
            name='Bedrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='poster',
            name='Car_spaces',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
