# Generated by Django 2.0 on 2019-05-20 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20190520_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='Bathrooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=10),
        ),
        migrations.AlterField(
            model_name='poster',
            name='Car_spaces',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=10),
        ),
        migrations.AlterField(
            model_name='poster',
            name='Price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Price'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='Property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.PropertyType'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='new_or_established',
            field=models.CharField(choices=[('New', 'New'), ('Established', 'Established')], max_length=20),
        ),
    ]
