# Generated by Django 2.0 on 2019-11-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_savereport_user_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savereport',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
