# Generated by Django 2.0 on 2019-05-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20190521_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
