# Generated by Django 2.0 on 2019-05-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_poster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='Price',
            field=models.CharField(max_length=2000),
        ),
    ]
