# Generated by Django 2.0 on 2019-05-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20190523_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
