# Generated by Django 2.0 on 2019-05-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20190523_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='Property_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment & Unit', 'Apartment & Unit'), ('Townhouse', 'Townhouse'), ('Villa', 'Villa'), ('Land', 'Land'), ('Acreage', 'Acreage'), ('Rural', 'Rural'), ('Block Of Units', 'Block Of Units'), ('Retirement Living', 'Retirement Living')], max_length=100),
        ),
    ]
