# Generated by Django 2.0 on 2019-05-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20190523_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='Bathrooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='poster',
            name='Bedrooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='poster',
            name='Car_spaces',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='poster',
            name='Property_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment & Unit', 'Apartment & Unit'), ('Townhouse', 'Townhouse'), ('Villa', 'Villa'), ('Land', 'Land'), ('Acreage', 'Acreage'), ('Rural', 'Rural'), ('Block Of Units', 'Block Of Units'), ('Retirement Living', 'Retirement Living')], default='House', max_length=100),
        ),
        migrations.AlterField(
            model_name='poster',
            name='new_or_established',
            field=models.CharField(choices=[('New', 'New'), ('Established', 'Established')], default='New', max_length=20),
        ),
    ]
