# Generated by Django 2.0 on 2019-05-25 02:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20190525_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='id',
        ),
        migrations.AddField(
            model_name='poster',
            name='id_user',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
